pin selenium==4.2
needed due to DashComposite AttributeError: 'WebDriver' object has no attribute 'find_element_by_css_selector' (see https://stackoverflow.com/a/72754667)